# Generated by Django 4.2 on 2024-11-03 19:34

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('cin', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[userapp.models.cin_validator], verbose_name='CIN')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='prenom')),
                ('num_tel', models.CharField(max_length=150, verbose_name='numbero de telephone')),
                ('adresse', models.CharField(max_length=150, verbose_name='adresse')),
                ('mail', models.CharField(max_length=150, validators=[userapp.models.email_validator], verbose_name='mail')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('mot_de_passe', models.CharField(max_length=150, verbose_name='mot de passe')),
                ('role', models.CharField(max_length=150, verbose_name='role')),
            ],
        ),
    ]
