# Generated by Django 4.2 on 2024-12-14 18:23

import conducteurapp.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conducteur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nb_jetons', models.IntegerField(default=0, verbose_name='nombre de jetons')),
                ('assurance', models.CharField(max_length=100, validators=[conducteurapp.models.validate_assurance], verbose_name="nom d'assurance")),
                ('vehicule', models.CharField(max_length=1000, validators=[conducteurapp.models.validate_vehicule], verbose_name='description du vehicule')),
                ('note', models.FloatField(default=0, verbose_name='note')),
                ('num_permis', models.CharField(max_length=12, validators=[conducteurapp.models.permis_validator], verbose_name='numero de permis')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('userapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
