# Generated by Django 4.2 on 2024-11-24 02:10

import conducteurapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='assurance',
            field=models.CharField(max_length=100, validators=[conducteurapp.models.validate_assurance], verbose_name="nom d'assurance"),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='num_permis',
            field=models.CharField(max_length=12, validators=[conducteurapp.models.permis_validator], verbose_name='numero de permis'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='vehicule',
            field=models.CharField(max_length=1000, validators=[conducteurapp.models.validate_vehicule], verbose_name='description du vehicule'),
        ),
    ]
