# Generated by Django 5.1.3 on 2024-12-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurapp', '0002_alter_conducteur_assurance_and_more'),
        ('conducteurapp', '0002_alter_conducteur_note'),
    ]

    operations = [
    ]
