# Generated by Django 4.2 on 2024-11-24 02:37

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=150, validators=[userapp.models.email_validator], verbose_name='mail'),
        ),
    ]
