# Generated by Django 4.2 on 2024-12-07 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default='test.jpg', upload_to='static/img/users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='only png and jpg files allowed')]),
        ),
    ]
