# Generated by Django 5.1.3 on 2024-11-25 09:32

import Rides.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='The name can only contain alphanumeric characters.', regex='^[\\w\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(error_messages={'required': 'The departure date and time are required.'}, validators=[Rides.models.validate_future_date])),
                ('start_point', models.CharField(error_messages={'invalid': "The start point must be 'town, Tunisia'."}, max_length=255, validators=[Rides.models.validate_city_town])),
                ('destination', models.CharField(error_messages={'invalid': "The destination must be 'town, Tunisia'."}, max_length=255, validators=[Rides.models.validate_city_town])),
                ('available_seats', models.PositiveIntegerField(default=0, error_messages={'invalid': 'Please enter a valid number of available seats.', 'max_value': 'The number of available seats cannot be more than 4.', 'min_value': 'The number of available seats cannot be less than 1.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('price', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Please enter a valid price.', 'max_value': 'The price cannot be more than 15 DT.', 'min_value': 'The price must be greater than 0.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('is_recurring', models.CharField(choices=[('ponctuel', 'Single Trip'), ('recurrent', 'Recurring Trip')], default='ponctuel', error_messages={'invalid_choice': "Please choose between 'Single Trip' or 'Recurring Trip'."}, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Rides.ride')),
            ],
        ),
    ]
