# Generated by Django 4.2 on 2024-12-18 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='owner',
            field=models.ForeignKey(blank=True, default=24, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
