# Generated by Django 5.1.3 on 2024-11-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0001_initial'),
        ('avisApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Rides.ride'),
        ),
    ]
