# Generated by Django 4.2 on 2024-12-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0001_initial'),
        ('avisApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='bad_comment_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='contains_bad_words',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Rides.ride'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='Rides.ride'),
        ),
    ]
