# Generated by Django 5.1.3 on 2024-11-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0001_initial'),
        ('avisApp', '0003_avis_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='Rides.ride'),
        ),
    ]
