# Generated by Django 5.1.3 on 2024-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisApp', '0004_alter_avis_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='contains_bad_words',
            field=models.BooleanField(default=False),
        ),
    ]
