# Generated by Django 5.1.3 on 2024-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisApp', '0005_avis_contains_bad_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='bad_comment_detected',
            field=models.BooleanField(default=False),
        ),
    ]
