# Generated by Django 4.2 on 2024-11-20 23:21

from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conducteur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userapp.user')),
                ('nb_jetons', models.IntegerField(default=0, verbose_name='nombre de jetons')),
                ('assurance', models.CharField(max_length=100, verbose_name="nom d'assurance")),
                ('vehicule', models.CharField(max_length=1000, verbose_name='description du vehicule')),
                ('note', models.FloatField(verbose_name='note')),
                ('num_permis', models.CharField(max_length=12, validators=[userapp.models.cin_validator], verbose_name='numero de permis')),
            ],
            bases=('userapp.user',),
        ),
    ]
