# Generated by Django 4.2 on 2024-11-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='note',
            field=models.FloatField(default=0, verbose_name='note'),
        ),
    ]
