# Generated by Django 4.2 on 2024-11-22 20:00

import Catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(validators=[Catalogue.models.validate_future_date], verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('price', models.IntegerField(verbose_name='prix')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
