# Generated by Django 5.1.2 on 2024-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauth",
            name="cin",
        ),
        migrations.AddField(
            model_name="userauth",
            name="carModel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userauth",
            name="licensePlate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userauth",
            name="role",
            field=models.CharField(
                choices=[("conducteur", "Conducteur"), ("passenger", "Passenger")],
                default="passenger",
                max_length=10,
            ),
        ),
    ]
