# Generated by Django 5.1.2 on 2024-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_remove_userauth_cin_userauth_carmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauth",
            name="role",
            field=models.CharField(
                choices=[("conducteur", "Conducteur"), ("passenger", "Passenger")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
