# Generated by Django 5.1.2 on 2024-11-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_alter_userauth_role_alter_userauth_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauth",
            name="carModel",
        ),
        migrations.RemoveField(
            model_name="userauth",
            name="licensePlate",
        ),
        migrations.RemoveField(
            model_name="userauth",
            name="role",
        ),
    ]
