# Generated by Django 4.2 on 2024-11-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userapp.user')),
                ('nb_jetons', models.IntegerField(default=0, verbose_name='nombre de jetons')),
            ],
            bases=('userapp.user',),
        ),
    ]
